### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Polyana-Fontes** [wildex999/TickDynamic#25]
I downloaded the latest dev version for kcauldron and installed on my server, on the first time it appeared to be running fine but I tested only by few seconds alone on the server, then I tried to create a group to prioritize cars and vehicles from MCHeli and Vehicular Movement mods over other entities, so I changed the config file and restarted the server, but when the server restarted it was unplayable with an massive amount of lag and I was alone on the server exactly as my first contact, so I removed the blocks that I added to the config and rebooted the server again but the problem persisted. I tried to delete the config file, re-upload the mod JAR and reboot many times but the problem seems to be getting worst every time I restart the server....

![image](https://cloud.githubusercontent.com/assets/3679022/12707085/c67b867e-c86d-11e5-8a9d-ed173706e00d.png)

I don't know why it was soo smooth on the first time and now it's just unplayable.

**Comment by Polyana-Fontes** [comment]
The tick time seems to be increasing if I leave the server running on this condition...
![image](https://cloud.githubusercontent.com/assets/3679022/12707116/242359a0-c86e-11e5-9e3b-b8ab28467c2d.png)

**Comment by Polyana-Fontes** [comment]
Turns out it caused a corruption in one mod that I don't know yet because the problem persisted after I removed TickDynamic from the mods dir, I'm going to investigate what happened exactly and I'll update this issue when I have more information.

**Comment by spannerman79** [comment]
> Turns out it caused a corruption in one mod

Which mod exactly? the hash value of the mod that is on your server? For both tickdynamic and this "corrupt" mod

Did you actually read the release notes and set the values of `max-tick-time` for both `tile` & `entity` to `1000`within `spigot.yml`?

**Comment by wildex999** [comment]
Hey, thank you for taking the time to describe the problem you have =)

Looking at the first screenshot you provided, it seems that the lag happens not at any one Entity or TileEntity, as it seems to only allocate 1,88 ms(Should be much higher) to Overworld.
This tells me that there is something outside the ticking of Entities/TileEntities which is causing the lag. 
It might be as you said, some corruption which uses time outside the normal ticking loop.

Were there any noticeable errors or unusual log output when you first added the TickDynamic groups which caused the problem?
Could you maybe paste the latest log on pastebin or something, and link it here?

Would it be possible for you to send me the world(And mods/config folder), or is the world too big?

If you can't send it, can you try backing up the world(Completely) and removing the mods MCHeli & Vehicular Movement(Try removing one at a time with a restart each) and see if that fixes the lag.
This would allow me to more accurately pin down what causes the problem. It seems that since it worked fine before you added that group, that it is in one of these mods.

Thank you for your time =)

**Comment by Polyana-Fontes** [comment]
Hi, the world has over 8 GB, it's too big.

The release notes didn't mention about `max-tick-time`:
![image](https://cloud.githubusercontent.com/assets/3679022/12726654/87b5a836-c8f7-11e5-92c2-5331ca43af53.png)

The problem seems to be with Applied Energistics, it seems to be adding `Callable` objects on a queue in an increasing ramp
![image](https://cloud.githubusercontent.com/assets/3679022/12726809/5a733202-c8f8-11e5-8c7e-9fcb28b982a2.png)

The group sections that I added to the config doesn't seems to be the cause of the issue because I restored an earlier backup and I tried to the TickDynamic mod again with default configs and the lag problem started again.

I'm going to do more tests until I find the exact steps to produce this problem.

**Comment by wildex999** [comment]
Yeah, I don't think I mentioned max-tick-time in the dev releases, but that doesn't seem to be the problem here.

I don't think the problem is with Applied Energistics, as that only seems to be what is causing a chunk to load. The problem seems to be in the NBTTagList. Most likely something was corrupted during the writing of NBT data for a block, entity or even the chunk itself, causing it to spend a lot of time trying to read the data.

This does indeed seem like a serious problem, but I'll have to dig deeper into it to figure out what TickDynamic could have done to cause it. The mod should have nothing to do with the reading or writing of NBT data at all.

**Comment by spannerman79** [comment]
There was always a known issue with rv2 that was fixed in rv3 in regards to a ME drive cycling loading of the chunk it's in over and over.

This was fixed via https://github.com/Gamealition/Applied-Energistics-2/commit/0a4742ddd498a339f4114be7fddc0e0584de83a9

Which version of AE2 is being used?

**Comment by wildex999** [comment]
I have tried to replicate this, placing a large AE2 network over multiple chunks, and then unloading/reloading the chunks. Nothing yet =/

What version of kCauldron do you use?

**Comment by spannerman79** [comment]
For the sake of testing remove tick dynamic fully reset configuration files wipe world and start a new test instance. If the issue persists then it's not a tick dynamic issue and this issue should be closed.

**Comment by wildex999** [comment]
@joserobjr I have released development version 3 now, do you think you could try using that and see if it still corrupts the world?
https://github.com/wildex999/TickDynamic/releases

**Comment by Polyana-Fontes** [comment]
@wildex999 It worked fine with that version
