### ISSUE TITLE
BigReactors (and other TileEntities using Server TPS for calculation) problems

### ISSUE THREAD

**Issue by GunArm** [wildex999/TickDynamic#7]
As detailed in this thread http://forum.feed-the-beast.com/threads/1-7-10-cauldron-1-8-tick-dynamic-keep-your-server-running-at-20-tps.61903/ BR uses TPS to make calculations, rather than just relying on tileEntity updates.  The thread details an issue with an actively cooled reactor using water faster than a choked transfer pipe could supply.  

I wanted to add that there are issues with passive reactors as well.  In our BTP world, the reactor is putting out 2.4 times as much energy as it says it is in the reactor control block, and I'd assume burning 1/2.4 times the amount of fuel it should for it's energy output.  You'd think I'd like this free energy ;p  but throws the game balance out of whack, and makes the numbers wrong.

I am sure 2.4 is contextual to our particular world and the number of updates that are being skipped per tick, I am guessing the worse the server lag, the more "free energy" will be produced.

**Comment by wildex999** [comment]
Yeah, it happens due to the skipping ticks, so it should give as much energy as if it was running at a clean 20 TPS.
However, it should also consume fuel/water etc. as if it was running at 20 TPS, so it should not be "free" energy.
So it should run out of fuel 2.4 times faster.
Can you confirm this?

**Comment by GunArm** [comment]
I am willing to, however I'm not exactly sure how to do it.  For measuring power output I put a teir3 EIO conduit coming straight out of my reactor power port and measured the throughput with a conduit probe and compared to the power output number in the reactor controller interface.  I'm not exactly sure how to get an "actual" number for burn rate, to compare to the one in the interface.

**Comment by wildex999** [comment]
Ok, I just did a test on my server.

First i set up a simple Reactor, with a single fuel rod, and have it a single Yellorium ingot.
Then I put an empty Energy Cell on the power output, and started it, with TickDynamic disabled.
I let it run until It used up a certain amount of fuel, noting that it takes 1mB of fuel every second, and noting the resulting energy in the Energy Cell.

Then I reset it all, and started it with TickDynamic enabled.
I loaded the server with TileEntities until it was running with a TileEntity TPS of ~5.
Noting again that is uses exactly 1 mB of fuel per second, I let it run to the same amount of remaining fuel.
The Energy Cell show the exact same amount of energy gathered.

So, it seems that it will give the exact same energy, and use the exact same amount of fuel, independent of the TileEntity TPS.
So, no free energy it seems =)

So the player has to take into account that the Reactor will use fuel, and produce energy at the server TPS. 
Of course, Tick Dynamic is not meant to be a replacement of fixing what is causing the low TPS in the first place ;)

**Comment by wildex999** [comment]
As for the Conduit showing a larger energy output than the Controller.
Let's say the TileEntity TPS is 10 TPS, and the Reactor is producing 10 RF/t.
However, while the Reactor is producing 10 RF/t, it's actually giving you for 20 TPS.
So every OTHER tick, it will output 20 RF.
As the TileEntity TPS goes lower, it will seem like it's producing more power, because it's giving it over less ticks.

**Comment by GunArm** [comment]
Ah good test.  The hurdle in my mind was how to load up a test world with enough junk to bring the Tile Entity TPS down or even measure that.

I want to say first of all that I think this is a great mod and a great idea.  So good infact, I almost think Mojang should have thought about it and implemented something similar into the core of minecraft to begin with.  But I'm a little worried by this.

I get what you are saying about the fuel.  Essentially we are NOT getting extra efficiency in terms of RF/ingot of fuel.  However, relative to the TileEntities consuming power at a rate bound to their (reduced) TileEntity TPS, the reactor is still over-producing (in RF/TileEntity tick).  Essentially, as the server gets more loaded, time moves faster for the reactor (relative to the energy-consumers for which time and thus consumption is going slower).  For each "second" my laser drill has to use power, my reactor has 2.4 seconds to generate power (speaking in loose terms, and I know 2.4 is just my personal current situation).  The more I load up the server, the more energy the same reactor can make, in the time my laser drill can spend a constant amount.  (This is really hard to think about.  Reminds me of general relativity.)

What worries me is, is there even anything that can be done to fix this?  You had proposed adding a configurable TileEntity exception list, for the water transfer nodes to keep the reactor full.   But, almost all these TileEntities are power-consumers, wouldn't we have to add almost all power consuming machines to that list, to preserve a semblance of the balance intended by the modpack author (having carefully chosen a power multiplier they thought was appropriate)?

I don't mean to be repetitive or write a (bigger) novel, but here's an example which you probably don't need: Bevo was very concerned about BigReactors being overpowered, and really choked the multiplier down for his pack.  I have a reactor that's supposed to only put out 30kRF/t.  Server gets loaded and we add tickdynamic, and tileEntity updates get reduced by half, while reactor stays constant.  Even if we excuse the reactor control block from TPS reduction (so that the Controller's RF/t number atleast displays what is actually being made available for the TileEntity's to use each TileEntity tick) the number is going to be double what it should be, 60kRF/t.  Which is higher than Bevo thought was appropriate.  And if we need more power, theoretically we can just throw down more TileEntities load the server more and slow the consumption/production ratio.  I can run 3 laser drills off of this reactor, and not make any turbines.  I hope there is a way around this, because I really do think this mod is a great idea.

Is the only sane way to fix it, to try to get BigReactors to change the way they calculate power output (or make it configurable), or inject code into that mod to change it forcefully?

Also, I wonder how many other mod's tile entities do calculations off of server TPS instead of TileEntity updates.  I presume the reason to do it that way would be a well-meaning attempt to reduce the TileEntity lag in the first place, never imagining that Server TPS and TileEntity TPS woudln't be the same.  If Mojang had only done this from the beginning, people would be writing code with this nuance in mind.

**Comment by wildex999** [comment]
The only mods that I can see that would do the calculations independent of TileEntity TPS, is mods with multiblock structures, as they would not logically have one block in the structure that do the calculations, but rather see all the blocks as a single entity.

Also when it comes to balance. You can't really look at it as the Reactor producing double the power in a given time, but rather that the consumers are consuming at at half the rate.
If the modpack set the reactor to output 30RF/t, it will output 20*30 = 600 RF/s, however the consumers will see it as 60RF/t, because they count two ticks in a single tick.
This does mean that you apparently get more power in a shorter time, but you really don't, as the operations will still take the same amount of time as if it was running at the full 20 TPS and having to wait for more power.
You say you can run 3 laser drills at the same energy source as 1 drill, but that means that each drill is still running at 1/3 the speed.

The only reason I mention having water sources be exempt from the slowdown is because:
1. They are usually run without power 
2. They are vital to make things not explode
Of course, the Reactor does not explode(I think?), but will run less efficient at high temperatures.

So Big Reactors(And any other Multiblock structure that run on Server TPS) will be a link in the chain which will have to be taken into account. However, they will also balance themself out, as the output will be consumed slowed. That means that any batteries will fill out, and the Reactor will stop producing power.
Also, fuel input will be slower, as any Quarries that mines Yellorium will run slower.

So what you really have to look at is, how often will the server run at a reduced speed?
Tick Dynamic is primarily meant for a way to smooth our lag spikes, and make the server playable at peak hours. It's not meant to permanently run TileEntities at < 20 TPS, so the players should not be able to run 3 Lasers from their one Reactor most of the time.
With the addition of user accounting, the player itself will be accountable for being slowed down, and have to take that into account. (I will provide a way for the player to be notified when they are slowed down).

Of course, I will try to add more configuration options to my mod as these problems become more apparent =)

**Comment by GunArm** [comment]
Ah ok this makes sense to me!
